# Generated by Django 2.2.12 on 2020-08-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WagyuInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagyu_recognition_id', models.CharField(max_length=255, verbose_name='個体識別番号')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(max_length=255, verbose_name='性別')),
                ('kind', models.CharField(max_length=255, verbose_name='種別')),
                ('date_of_dead', models.DateField(verbose_name='と畜日')),
            ],
        ),
    ]
