# Generated by Django 3.1.4 on 2021-01-03 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagyuer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagyupackageimg',
            name='upload_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wagyupackageimg',
            name='img',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='アップロード画像'),
        ),
    ]
