# Generated by Django 3.1.4 on 2021-01-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagyuer', '0003_auto_20210103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagyupackageimg',
            name='img',
            field=models.ImageField(upload_to='uploads/', verbose_name='アップロード画像'),
        ),
    ]
