# Generated by Django 3.1.4 on 2021-01-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagyuer', '0008_auto_20210103_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='wagyu_infomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='個体識別番号')),
                ('kind', models.CharField(blank=True, max_length=255, null=True, verbose_name='種別')),
                ('sex', models.CharField(blank=True, max_length=255, null=True, verbose_name='性別')),
                ('birth_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='出生日')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='出生場所')),
                ('slaughter_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='と畜日')),
                ('slaughter_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='と畜場所')),
            ],
        ),
        migrations.AlterField(
            model_name='wagyupackageimg',
            name='img',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='アップロード画像'),
        ),
    ]
