# Generated by Django 3.1.4 on 2021-01-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagyuer', '0009_auto_20210103_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wagyu_infomation',
            new_name='WagyuInfomation',
        ),
    ]
