# Generated by Django 3.1.4 on 2021-01-03 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagyuer', '0012_wagyuinfomation_wagyu_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagyuinfomation',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
